/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tdd.kata

import org.junit.Test
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class TicTacToeTest {

    @Test
    fun thatGameIsNotOverAtTheBeginning() {
        val ticTacToe = TicTacToe()

        assertFalse(ticTacToe.gameOver())
    }

    @Test
    fun thatGameIsOverWhenEverythingIsTaken() {
        val ticTacToe = TicTacToe(arrayOf(arrayOf(1, 1, 1), arrayOf(1, 1, 1), arrayOf(1, 1, 1)))

        assertTrue(ticTacToe.gameOver())
    }

    @Test
    fun aGameIsNotOverWhenAllFieldsInAColumnAreTakenByAPlayer() {
        val ticTacToe = TicTacToe(arrayOf(arrayOf(1, 1, 1), arrayOf(0, 0, 0), arrayOf(0, 0, 1)))

        assertFalse(ticTacToe.gameOver())
    }

    @Test
    fun aGameIsNotOverWhenAllFieldsInAColumnAreTakenByDifferentPlayers() {
        val ticTacToe = TicTacToe(arrayOf(arrayOf(1, 1, 1), arrayOf(-1, -1, -1), arrayOf(0, 0, 0)))

        assertFalse(ticTacToe.gameOver())
    }

    @Test
    fun aGameIsOverWhenAllFieldsInAColumnAreTakenByAPlayer() {
        val ticTacToe = TicTacToe(arrayOf(arrayOf(1, 1, 1), arrayOf(0, 0, 1), arrayOf(0, 0, 1)))

        assertTrue(ticTacToe.gameOver())
    }
}
