/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tdd.kata

import kotlin.test.assertEquals


class TicTacToeTest {
    private val ticTacToe = TicTacToe()

    @org.junit.Test
    fun thatGameIsOverWhenAllFieldsAreTaken() {
        assertEquals(ticTacToe.allFieldsTaken(), ticTacToe.gameOver())
    }

    @org.junit.Test
    fun thatGameIsOverWhenAllFieldsInAColumnAreTakeByPlayerOne() {
        assertEquals(ticTacToe.gameOver(), ticTacToe.allFieldsInOneColumnAreTakenByPlayerOne())
    }

    @org.junit.Test
    fun thatGameIsOverWhenAllFieldsInAColumnAreTakeByPlayerTwo() {
        assertEquals(ticTacToe.gameOver(), ticTacToe.allFieldsInOneColumnAreTakenByPlayerTwo())
    }
}
