/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tdd.kata

import kotlin.math.abs

class TicTacToe(
    private var gameState: Array<Array<Int>> = arrayOf(arrayOf(0, 0, 0), arrayOf(0, 0, 0), arrayOf(0, 0, 0))
) {
    private var playerTurn = 1

    fun hasGameFinished(): Boolean {
        return areAllFieldsInOneColumnTaken() ||
                areAllFieldsInOneRowTaken() ||
                areDiagonalsTakenForOnePlayer() ||
                haveAllFieldsBeenTaken()
    }

    private fun haveAllFieldsBeenTaken(): Boolean {
        return gameState.flatten().contains(0).not()
    }

    private fun areAllFieldsInOneColumnTaken(): Boolean {
        val rowOne = abs(gameState[0][0] + gameState[1][0] + gameState[2][0]) == 3
        val rowTwo = abs(gameState[0][1] + gameState[1][1] + gameState[2][1]) == 3
        val rowThree = abs(gameState[0][2] + gameState[1][2] + gameState[2][2]) == 3

        return rowOne || rowTwo || rowThree
    }

    private fun areAllFieldsInOneRowTaken(): Boolean {
        val rowOne = abs(gameState[0][0] + gameState[0][1] + gameState[0][2]) == 3
        val rowTwo = abs(gameState[1][0] + gameState[1][1] + gameState[1][2]) == 3
        val rowThree = abs(gameState[2][0] + gameState[2][1] + gameState[2][2]) == 3

        return rowOne || rowTwo || rowThree
    }

    private fun areDiagonalsTakenForOnePlayer(): Boolean {
        val diagonalOne = abs(gameState[0][0] + gameState[1][1] + gameState[2][2]) == 3
        val diagonalTwo = abs(gameState[0][2] + gameState[1][1] + gameState[2][0]) == 3

        return diagonalOne || diagonalTwo
    }

    private fun isTurnOf(player: Int): Boolean {
        if (player == playerTurn) {
            playerTurn *= (-1)
            return true
        }

        return false
    }

    fun take(i: Int, j: Int, value: Int): Boolean {
        if (gameState[i][j] == 0 && isTurnOf(value)) {
            gameState[i][j] = value
            return true
        }

        return false
    }
}
