/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tdd.kata

class TicTacToe {
    fun allFieldsTaken() = true

    fun gameOver() = true

    fun allFieldsInOneColumnAreTakenByPlayerTwo(): Boolean {
        return true
    }

    fun allFieldsInOneColumnAreTakenByPlayerOne(): Boolean {
        return true
    }
}
