/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tdd.kata

import kotlin.math.abs

class TicTacToe(
    private var gameState: Array<Array<Int>> = arrayOf(arrayOf(0, 0, 0), arrayOf(0, 0, 0), arrayOf(0, 0, 0))
) {

    fun gameOver(): Boolean {

        var fieldsTaken = 0
        for (row in gameState) {
            for (columnRow in row) {
                if (columnRow != 0) {
                    fieldsTaken++
                }
            }
        }
        return areAllFieldsInOneColumnTaken() || areAllFieldsInOneRowTaken() || areDiagonalsTakenForOnePlayer() || (fieldsTaken == 9)
    }

    private fun areAllFieldsInOneColumnTaken(): Boolean {
        val sumOfColumns = arrayOf(0, 0, 0)
        for (row in gameState) {
            for ((index, field) in row.withIndex()) {
                sumOfColumns[index] += field
            }
        }

        return (abs(sumOfColumns[0]) == 3 || abs(sumOfColumns[1]) == 3 || abs(sumOfColumns[2]) == 3)
    }

    private fun areAllFieldsInOneRowTaken(): Boolean {
        for (row in gameState) {
            var sumOfFieldValues = 0
            for (field in row) {
                sumOfFieldValues += field
            }
            if (abs(sumOfFieldValues) == 3) return true
        }
        return false
    }

    fun areDiagonalsTakenForOnePlayer(): Boolean {
        val diagonalOne = abs(gameState[0][0] + gameState[1][1] + gameState[2][2]) == 3
        val diagonalTwo = abs(gameState[0][2] + gameState[1][1] + gameState[2][0]) == 3
        return diagonalOne || diagonalTwo
    }
}
